config/routes.rb
Rails.application.routes.draw do

  resources :rooms do
    resources :messages
  end

  root 'pages#home'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  #retorna todas as salas que NÃO estejam privadas
  after_create_commit { broadcast_append_to "rooms" }

  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, -> (user) { where.not(id: user)}
  #isso vai listar todos os usuarios on, menos o usuario logado

  after_create_commit { broadcast_append_to "users" }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @current_user = current_user
    @message = @current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end


  private
    def msg_params
      params.require(:message).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    #@single_room = Room.find(params[:id])
    @users = User.all_except(current_user)
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @room = Room.new

    @users = User.all_except(@current_user)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render "index"
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(format: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom dale">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <i class="fa-brands fa-discord fa-3x icone"></i>
      <h5 class="dcria">Discord dos cria</h5>
    </a>
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="#" class="nav-link px-3 link-light link-menu">Baixar</a></li>
      <li><a href="#" class="nav-link px-3 link-light link-menu">Nitro</a></li>
      <li><a href="#" class="nav-link px-3 link-light link-menu">Segurança</a></li>
      <li><a href="#" class="nav-link px-3 link-light link-menu">Suporte</a></li>
      <li><a href="#" class="nav-link px-3 link-light link-menu">Blog</a></li>
      <li><a href="#" class="nav-link px-3 link-light link-menu">Carreiras</a></li>
    </ul>
    <div class="col-md-3 text-end butao-usuario">
      <% if current_user %>
        <%= link_to "Sair", destroy_user_session_path, data: { turbo_method: :delete, turbo_confim: "tem certeza ?" }, class: "btn btn-light botao-link"%>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-light botao-link"%>
        <%= link_to "Nova conta", new_user_registration_path, class: "btn btn-light botao-link"%>
      <% end %>
    </div>
</header>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
    <%= form_with(model: [@single_room, @message], remote: true, class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } ) do |f| %>
        <%= f.text_field :body, id: "chat-text", class: "form-group msg-form", autocomplete: 'off' %>
        <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
    <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.text_field :name, class: "form-control", autocomplete: "off" %>
    <%= f.submit "Criar Sala", data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7d639ddac3.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      <%= ".msg-#{current_user&.id}"%> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end;
      }
    </style>

  </head>

  <body>
    <div class>
      <%= render "layouts/navbar" %>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
    <div class="message-box msg-<%= message.user.id %>">
        <% unless message.room.is_private %>
            <h6 class="name text-light"><%= message.user.email %></h6>
        <% end %>

        <div class="text-light">
            <%= message.body %>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<h1>discord dos cria</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
    <%= link_to "Inicie uma conversa", rooms_path %>
<% end %>

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room, class: "text-success nome-room" %>
</div>

app/views/rooms/index.html.erb
<h1>Menu</h1>

<div class="row">
    <div class="col-md-2 bg-dark text-light tabela-user-room"><br>
        <p>logado como: <%= @current_user.email %></p><hr>

        <h4>Usuarios on</h4>
        <div>
            <%= turbo_stream_from "users" %>
            <div id="users">
                <%= render @users %>
                <hr>
            </div>
        </div>

        <h4>Salas </h4>
        <%= render partial: "layouts/new_room_form" %><br>
        <div>
            <%= turbo_stream_from "rooms" %>
            <div id="rooms">
                <%= render @rooms %>
            </div>
        </div>
        <br>
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-9 bg-dark chat">
        <% if @single_room %>
            <div id="single_room">
                <h4 class="text-center text-light"><%= @single_room.name %></h4><hr class="linha-room">

                <%= turbo_stream_from @single_room %>
                <div id="messages">
                    <%= render @messages %>
                </div>

                <%= render partial: "layouts/new_message_form" %>
            </div>

        <% end %>
    </div>
</div>
<br>
<br>

app/views/users/_user.html.erb
<div>
    <%= link_to user.email, users_path %>
</div>